import 'dart:async';
import 'package:flutter/material.dart';
import '../../../models/container_model.dart';
import '../../../models/driver_model.dart';
import '../../../models/trip_model.dart';
import '../../../models/vehicle_model.dart';
import '../../../utils/app_theme.dart';
import '../../../widgets/corridor_map_widget.dart';
import '../../../widgets/sensor_telemetry_card.dart';

class DriverHomeTab extends StatefulWidget {
  final DriverProfile driver;
  final VehicleInfo vehicle;
  final TripInfo? activeTrip;
  final ContainerInfo? container;
  final Stream<SensorTelemetry>? telemetryStream;
  final bool isOnDuty;
  final ValueChanged<bool> onDutyChanged;
  final VoidCallback onSosPressed;
  final VoidCallback onInspectionPressed;
  final VoidCallback onIncidentReportPressed;
  final VoidCallback onTripActionPressed;
  final VoidCallback onViewRoutesPressed;
  final VoidCallback onNextStopReached;
  final List<String> recentAlerts;

  const DriverHomeTab({
    super.key,
    required this.driver,
    required this.vehicle,
    required this.activeTrip,
    this.container,
    this.telemetryStream,
    required this.isOnDuty,
    required this.onDutyChanged,
    required this.onSosPressed,
    required this.onInspectionPressed,
    required this.onIncidentReportPressed,
    required this.onTripActionPressed,
    required this.onViewRoutesPressed,
    required this.onNextStopReached,
    required this.recentAlerts,
  });

  @override
  State<DriverHomeTab> createState() => _DriverHomeTabState();
}

class _DriverHomeTabState extends State<DriverHomeTab> {
  late ContainerInfo _container;
  StreamSubscription<SensorTelemetry>? _streamSub;

  @override
  void initState() {
    super.initState();
    _container = widget.container ?? ContainerInfo.mockPrimaryContainer;
    _subscribeToTelemetryStream();
  }

  void _subscribeToTelemetryStream() {
    if (widget.telemetryStream != null) {
      _streamSub = widget.telemetryStream!.listen(_onSensorTelemetryReceived);
    }
  }

  void _onSensorTelemetryReceived(SensorTelemetry telemetry) {
    if (!mounted) return;
    setState(() {
      // Security breach status is auto-generated by physical IoT hardware signals
      final isHardwareTampered = telemetry.isTampered;
      final securityStatus = isHardwareTampered
          ? ContainerSecurityStatus.tamperBreach
          : (_container.securityStatus == ContainerSecurityStatus.tamperBreach
              ? ContainerSecurityStatus.secure
              : _container.securityStatus);

      _container = _container.copyWith(
        securityStatus: securityStatus,
        telemetry: telemetry,
      );
    });
  }

  @override
  void didUpdateWidget(DriverHomeTab oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.container != null && widget.container != oldWidget.container) {
      _container = widget.container!;
    }
    if (widget.telemetryStream != oldWidget.telemetryStream) {
      _streamSub?.cancel();
      _subscribeToTelemetryStream();
    }
  }

  @override
  void dispose() {
    _streamSub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final trip = widget.activeTrip;

    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // ─── Figure 10: Current Trip Card ──────────────────────────────
          _buildCurrentTripCard(context, trip),

          const SizedBox(height: 16),

          // ─── Figure 10: Quick Stats Card ──────────────────────────────
          _buildQuickStatsCard(context),

          const SizedBox(height: 16),

          // ─── Figure 10: Emergency Alert Button ────────────────────────
          _buildEmergencyAlertButton(context),

          const SizedBox(height: 16),

          // ─── Truck & Assigned IoT Lock Card (Preserved from requirements) ──
          _buildTruckAndIotLockCard(context),

          const SizedBox(height: 16),

          // ─── Sensor Telemetry Card (Auto-Monitored via IoT Sensors) ─
          SensorTelemetryCard(
            container: _container,
          ),
        ],
      ),
    );
  }

  // ── Figure 10: Current Trip Card ──────────────────────────────────────
  Widget _buildCurrentTripCard(BuildContext context, TripInfo? trip) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 14,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header Row: Current Trip title + On Route Badge
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Row(
                children: [
                  Icon(Icons.navigation_rounded, size: 20, color: Color(0xFF0E3352)),
                  SizedBox(width: 8),
                  Text(
                    'Current Trip',
                    style: TextStyle(
                      fontSize: 17,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFF1E293B),
                      letterSpacing: 0.2,
                    ),
                  ),
                ],
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
                decoration: BoxDecoration(
                  color: const Color(0xFFDCFCE7),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: const Color(0xFF86EFAC)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Container(
                      width: 7,
                      height: 7,
                      decoration: const BoxDecoration(
                        color: Color(0xFF16A34A),
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 6),
                    const Text(
                      'On Route',
                      style: TextStyle(
                        color: Color(0xFF15803D),
                        fontWeight: FontWeight.bold,
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),

          const SizedBox(height: 14),

          // Container ID Row (Figure 10)
          Row(
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [Color(0xFFEFF6FF), Color(0xFFDBEAFE)],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: const Color(0xFFBFDBFE)),
                ),
                child: const Icon(
                  Icons.inventory_2_outlined,
                  color: Color(0xFF2563EB),
                  size: 20,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Container ID',
                      style: TextStyle(
                        fontSize: 11,
                        color: Color(0xFF64748B),
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    Text(
                      trip?.containerId ?? 'CTR-2024-8473',
                      style: const TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF1E293B),
                        letterSpacing: 0.3,
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFFF8FAFC),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: const Color(0xFFE2E8F0)),
                ),
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.sensors_rounded, size: 14, color: Color(0xFF475569)),
                    SizedBox(width: 4),
                    Text(
                      'GPS 3D Fix',
                      style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: Color(0xFF475569)),
                    ),
                  ],
                ),
              ),
            ],
          ),

          const SizedBox(height: 14),

          // Embedded Route Map (Figure 10: with route line & time badges)
          ClipRRect(
            borderRadius: BorderRadius.circular(14),
            child: GestureDetector(
              onTap: widget.onViewRoutesPressed,
              child: CorridorMapWidget(
                corridorTitle: trip?.routeName ?? 'Colombo Fort ➔ Orugodawaththa',
                originTitle: trip?.origin ?? 'Colombo Fort',
                destinationTitle: trip?.destination ?? 'Orugodawaththa',
                progress: 0.60,
                isDeviated: false,
                deviationMeters: 0.0,
                speedKmH: 42,
                height: 180,
                showSrsCallouts: true,
                showTopStatusOverlay: false,
              ),
            ),
          ),

          const SizedBox(height: 14),

          // Bottom Stats: Distance Left & ETA (Figure 10)
          Row(
            children: [
              Expanded(
                child: Container(
                  padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 12),
                  decoration: BoxDecoration(
                    color: const Color(0xFFF8FAFC),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: const Color(0xFFE2E8F0)),
                  ),
                  child: Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: const Color(0xFFEFF6FF),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Icon(Icons.near_me_rounded, color: Color(0xFF2563EB), size: 18),
                      ),
                      const SizedBox(width: 10),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Distance Left',
                            style: TextStyle(fontSize: 11, color: Color(0xFF64748B), fontWeight: FontWeight.w500),
                          ),
                          Text(
                            trip != null
                                ? '${(trip.totalDistanceKm - trip.coveredDistanceKm).toStringAsFixed(1)} km'
                                : '3.3 km',
                            style: const TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0F172A),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Container(
                  padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 12),
                  decoration: BoxDecoration(
                    color: const Color(0xFFF8FAFC),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: const Color(0xFFE2E8F0)),
                  ),
                  child: Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: const Color(0xFFFEF3C7),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Icon(Icons.access_time_filled_rounded, color: Color(0xFFD97706), size: 18),
                      ),
                      const SizedBox(width: 10),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'ETA',
                            style: TextStyle(fontSize: 11, color: Color(0xFF64748B), fontWeight: FontWeight.w500),
                          ),
                          Text(
                            trip != null ? '18 min' : '18 min',
                            style: const TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0F172A),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ── Figure 10: Quick Stats Card ───────────────────────────────────────
  Widget _buildQuickStatsCard(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 14,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      padding: const EdgeInsets.all(18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Quick Stats',
                style: TextStyle(
                  fontSize: 17,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF1E293B),
                ),
              ),
              Text(
                'Today',
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  color: Color(0xFF64748B),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              _buildModernStatTile(
                value: '24',
                label: 'Total Trips',
                icon: Icons.local_shipping_outlined,
                color: const Color(0xFF0F2537),
                bg: const Color(0xFFF1F5F9),
              ),
              const SizedBox(width: 10),
              _buildModernStatTile(
                value: '98%',
                label: 'On-Time',
                icon: Icons.verified_outlined,
                color: const Color(0xFF10B981),
                bg: const Color(0xFFECFDF5),
              ),
              const SizedBox(width: 10),
              _buildModernStatTile(
                value: '3.2k',
                label: 'km Total',
                icon: Icons.route_outlined,
                color: const Color(0xFF3B82F6),
                bg: const Color(0xFFEFF6FF),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildModernStatTile({
    required String value,
    required String label,
    required IconData icon,
    required Color color,
    required Color bg,
  }) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 8),
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: color.withValues(alpha: 0.15)),
        ),
        child: Column(
          children: [
            Icon(icon, color: color, size: 20),
            const SizedBox(height: 6),
            Text(
              value,
              style: TextStyle(
                fontSize: 19,
                fontWeight: FontWeight.w800,
                color: color,
              ),
            ),
            const SizedBox(height: 2),
            Text(
              label,
              style: const TextStyle(
                fontSize: 11,
                color: Color(0xFF64748B),
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Figure 10: Emergency Alert Button ─────────────────────────────────
  Widget _buildEmergencyAlertButton(BuildContext context) {
    return InkWell(
      onTap: widget.onSosPressed,
      borderRadius: BorderRadius.circular(16),
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Color(0xFFFFF1F2), Color(0xFFFEE2E2)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: const Color(0xFFFCA5A5), width: 1.2),
          boxShadow: [
            BoxShadow(
              color: const Color(0xFFEF4444).withValues(alpha: 0.10),
              blurRadius: 10,
              offset: const Offset(0, 3),
            ),
          ],
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: const BoxDecoration(
                color: Color(0xFFEF4444),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.notifications_active_rounded,
                color: Colors.white,
                size: 16,
              ),
            ),
            const SizedBox(width: 10),
            const Text(
              'Emergency Alert',
              style: TextStyle(
                color: Color(0xFFDC2626),
                fontWeight: FontWeight.bold,
                fontSize: 15,
                letterSpacing: 0.3,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Truck & Assigned IoT Lock Card (Preserved for tests) ───────────────
  Widget _buildTruckAndIotLockCard(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 10,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: AppTheme.customsBlue.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(Icons.lock_outline,
                    color: AppTheme.customsBlue, size: 20),
              ),
              const SizedBox(width: 10),
              const Expanded(
                child: Text(
                  'Truck & Assigned IoT Lock',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF1E293B),
                  ),
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFFDCFCE7),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Text(
                  'LOCK ARMED',
                  style: TextStyle(
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF15803D),
                  ),
                ),
              ),
            ],
          ),
          const Divider(height: 20),
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'TRUCK MODEL',
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0xFF94A3B8),
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      widget.vehicle.modelName,
                      style: const TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF0F172A),
                      ),
                    ),
                  ],
                ),
              ),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'TRUCK REGISTRATION',
                      style: TextStyle(
                        fontSize: 10,
                        color: Color(0xFF94A3B8),
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Truck Reg: ${widget.vehicle.plateNumber}',
                      style: const TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF0F172A),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: const Color(0xFFE2E8F0)),
            ),
            child: Row(
              children: [
                const Icon(Icons.nfc_rounded, size: 18, color: AppTheme.customsBlue),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Assigned Smart Lock: ${widget.vehicle.assignedLockId}',
                    style: const TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFF334155),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
